name: CI/CD - Replit & Railway

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Your production DB URL for tests if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      # Deploy to Replit
      - name: Deploy to Replit
        if: success()
        env:
          REPLIT_TOKEN: ${{ secrets.REPLIT_TOKEN }}
          REPLIT_PROJECT_ID: ${{ secrets.REPLIT_PROJECT_ID }}
        run: |
          echo "Deploying to Replit..."
          # Example deploy command using Replit CLI or API
          # Replace this with actual deploy commands you use
          curl -X POST "https://replit.com/api/v0/projects/${REPLIT_PROJECT_ID}/deploy" \
               -H "Authorization: Bearer $REPLIT_TOKEN"

      # Deploy to Railway
      - name: Deploy to Railway
        if: success()
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          echo "Deploying to Railway..."
          # Example using Railway CLI or API
          # Make sure Railway CLI is installed or use curl with API
          curl -X POST "https://api.railway.app/v1/projects/${RAILWAY_PROJECT_ID}/deploy" \
               -H "Authorization: Bearer $RAILWAY_TOKEN"

